apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: show-destination-rule
  namespace: mad
spec:
  host: show-service
  subsets:
    - labels:
        version: v1
      name: v1
