apiVersion: apps/v1
kind: Deployment
metadata:
  name: tool-deployment
  namespace: mad
  labels:
    app: tool
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tool
  template:
    metadata:
      labels:
        app: tool
    spec:
      serviceAccountName: internal-app
      containers:
        - name: tool
          image: ubuntu:latest
          command: ["sleep"]
          args: ["infinity"]
