apiVersion: apps/v1
kind: Deployment
metadata:
  name: show-deployment
  namespace: mad
  labels:
    app: show
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: show
      version: v1
  template:
    metadata:
      labels:
        app: show
        version: v1
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "internal-app"
        vault.hashicorp.com/agent-inject-secret-database-config.txt: "internal/data/database/config"
    spec:
      serviceAccountName: internal-app
      containers:
        - name: show
          image: aaronyunan/show:12
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
