apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: show-virutal-service
  namespace: mad
spec:
  gateways:
    - mad-gateway
  hosts:
    - "*"
  http:
    - route:
        - destination:
            host: show-service-cluster-ip
            port:
              number: 9090
      retries:
        attempts: 3
        perTryTimeout: 2s
        retryOn: 5xx
